#!/usr/bin/env bash
#script that transfers a file from our client to a server
# Check if the correct number of arguments are provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Use scp to transfer the file to the user's home directory on the server
# Disable strict host key checking using the "-o StrictHostKeyChecking=no" option
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
  echo "File transferred successfully to $username@$server_ip:~/"
else
  echo "File transfer failed."
fi

