#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart
