#!/usr/bin/env bash
# Installs and setup haproxy load balancer

# Replace [STUDENT_ID] with your actual student ID
STUDENT_ID="251219"
HAPROXY_CONFIG="
global
    maxconn 50000
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30000
    daemon

defaults
    log global
    mode http
    option tcplog
    option http-server-close
    option forwardfor
    timeout connect 5000
    timeout client 30000
    timeout server 30000

frontend my_frontend
    bind *:80
    stats uri /haproxy?stats
    default_backend my_backend

backend my_backend
    balance roundrobin
    server web-01 52.91.178.118:80 check
    server web-02 100.25.41.192:80 check
"
# Update the system
if ! command -v haproxy &> /dev/null
then
    sudo apt-get install --no-install-recommends software-properties-common
    sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
    sudo apt update
    #sudo apt upgrade -y

    # Install HAProxy
    sudo apt install -y haproxy=2.8.\*
fi

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup   # Backup the default configuration
echo -e "$HAPROXY_CONFIG" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAProxy management via init script
sudo systemctl enable haproxy
sudo service haproxy start


