#!/usr/bin/env bash
#Bash script that displays:
#    To infinity and beyond indefinitely
#    With a sleep 2 in between each iteration
#    I am invincible!!! when receiving a SIGTERM signal
# Function to display the message when receiving a SIGTERM signal
function on_sigterm {
  echo "I am invincible!!!"
  exit 0
}

# Trap the SIGTERM signal and call the 'on_sigterm' function
trap on_sigterm SIGTERM

# Loop to display "To infinity and beyond" indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 2
done
