#!/usr/bin/env bash
# This script displays different messages based on the loop iteration.
# Initialize a counter variable
counter=1
# Using a while loop to loop from 1 to 10
while [ $counter -le 10 ]
do
  if [ $counter -eq 4 ]; then
    echo "bad luck"
  elif [ $counter -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( counter++ ))
done
