#!/usr/bin/env bash
# Set the SSH private key file
private_key=~/.ssh/school

# Set the SSH user and server hostname or IP address
user=ubuntu
server=52.205.222.84

# Use ssh with single-character flags to connect
ssh "$user@$server" -i "$private_key"
